apiVersion: v1
kind: ServiceAccount
metadata:
  name: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      serviceAccountName: front
      containers:
        - name: front
          image: front
          ports:
            - containerPort: 8000
          command:
            - "uvicorn"
            - "app:app"
---
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
    service: front
spec:
  selector:
    app: front
  ports:
    - port: 8000
      name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: front-gateway
spec:
  # selector:
  #   istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front
spec:
  hosts:
    - "*"
  gateways:
    - front-gateway
  http:
    - route:
        - destination:
            host: front
            port:
              number: 8000
