apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
  labels:
    app: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      serviceAccountName: greeter
      containers:
        - name: greeter
          image: greeter
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: greeter
  labels:
    app: greeter
    service: greeter
spec:
  selector:
    app: greeter
  ports:
    - port: 50051
      name: grpc
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeter
spec:
  hosts:
    - greeter
  http:
    - route:
        - destination:
            host: greeter
            port:
              number: 50051
