apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      serviceAccountName: hello
      containers:
        - name: hello
          image: hello
          ports:
            - containerPort: 80
          command:
            - "uvicorn"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "80"
            - "app:app"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    service: httpbin
spec:
  selector:
    app: hello
  ports:
    - port: 8000
      name: http
      targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
spec:
  hosts:
    - "*"
  gateways:
    - hello-gateway
  http:
    - route:
        - destination:
            host: hello
            port:
              number: 8000
