apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: istio-sample
build:
  artifacts:
    - image: front
      context: front
    - image: hello
      context: hello
    - image: greeter
      context: greeter
deploy:
  kubectl:
    manifests:
      - front.yaml
      - hello.yaml
      - greeter.yaml
