apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: istio-sample
build:
  artifacts:
    - image: front
      context: front
    - image: hello
      context: hello
deploy:
  kubectl:
    manifests:
      - front.yaml
      - hello.yaml
